apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "keycloak-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keycloak-operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: keycloak-operator
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: keycloak-operator
          {{- with .Values.operator.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELATED_IMAGE_KEYCLOAK
              value: {{ .Values.operator.relatedKeycloakImage | quote }}
            - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKREALMIMPORTCONTROLLER_NAMESPACES
              value: {{ .Values.operator.watchNamespaces.realmImport | quote }}
            - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKCONTROLLER_NAMESPACES
              value: {{ .Values.operator.watchNamespaces.keycloak | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.operator.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.operator.probes.readiness | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.operator.probes.startup | nindent 12 }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
